#!/bin/sh

set -e

mkdir -p /var/db/ports/sudo
cat <<'EOF' > /var/db/ports/sudo/options
# This file is auto-generated by 'make config'.
# No user-servicable parts inside!
# Options for sudo-1.6.9.17
_OPTIONS_READ=sudo-1.6.9.17
WITHOUT_LDAP=true
WITHOUT_INSULTS=true
WITHOUT_SHELL_SETS_HOME=true
EOF

cd /usr/ports/security/sudo
make install

exit
